source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CHGInputAccessoryView_Example', :exclusive => true do
  pod "CHGInputAccessoryView", :path => "../"
end

target 'CHGInputAccessoryView_Tests', :exclusive => true do
  pod "CHGInputAccessoryView", :path => "../"

  
end
